### ISSUE TITLE
round优化

### ISSUE THREAD

**Issue by daheige** [hyperjiang/php#1]
https://github.com/hyperjiang/php/blob/51f0e3ff7a56c057f982c1eacb4091be2830a84d/math.go#L12
//对浮点数进行四舍五入操作比如 12.125保留2位小数==>12.13
func Round(f float64, n int) float64 {
	n10 := math.Pow10(n)
	return math.Trunc((f+0.5/n10)*n10) / n10
}

你写的是考虑了14位范围?

**Comment by hyperjiang** [comment]
go 1.10 以后已经自带Round函数了，我写这个函数的时候还是1.9，不记得为什么要限制14位范围了
