### ISSUE TITLE
undefined: syscall.Access

### ISSUE THREAD

**Issue by Sinevia** [hyperjiang/php#2]
# github.com/hyperjiang/php
..\..\pkg\mod\github.com\hyperjiang\php@v0.5.1\filesystem.go:109:9: undefined: syscall.Access
..\..\pkg\mod\github.com\hyperjiang\php@v0.5.1\filesystem.go:114:9: undefined: syscall.Access        
..\..\pkg\mod\github.com\hyperjiang\php@v0.5.1\filesystem.go:119:9: undefined: syscall.Access

**Comment by hyperjiang** [comment]
May I know your operating system? Is it windows?

**Comment by hyperjiang** [comment]
The windows issue is resolved, please use v0.6.0 version

**Comment by Sinevia** [comment]
Thank you @hyperjiang
